# Generated by Django 3.0.6 on 2020-09-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Representada',
            fields=[
                ('idcliente_representada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fiscal', models.CharField(max_length=45)),
                ('cif', models.CharField(max_length=45)),
                ('nombre_comercial', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=60)),
                ('telefono_corp_1', models.IntegerField()),
                ('telefono_corp_2', models.IntegerField(blank=True)),
                ('email_corp', models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Representada',
            fields=[
                ('idrepresentada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fiscal', models.CharField(max_length=45)),
                ('cif', models.CharField(max_length=45)),
                ('nombre_comercial', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=60)),
                ('telefono_corp_1', models.IntegerField()),
                ('telefono_corp_2', models.IntegerField(blank=True)),
                ('email_corp', models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Ventas',
            fields=[
                ('idstaff_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('telefono_movil', models.IntegerField(blank=True)),
                ('email', models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representacion',
            fields=[
                ('idrepresentacion', models.AutoField(primary_key=True, serialize=False)),
                ('idcliente_representada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Cliente_Representada')),
                ('idrepresentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Representada')),
                ('idstaff_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Staff_Ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_Representada',
            fields=[
                ('idcontacto_representada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('telefono_movil', models.IntegerField(blank=True)),
                ('email', models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True)),
                ('nivel_decision', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=45)),
                ('departamento', models.CharField(choices=[('PA', 'Propietario'), ('C', 'Comercial'), ('F', 'Financiero'), ('P', 'Producción')], max_length=45)),
                ('idrepresentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Representada')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_Cliente_Representada',
            fields=[
                ('idcontacto_cliente_representada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('telefono_movil', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('nivel_decision', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=45)),
                ('departamento', models.CharField(choices=[('PA', 'Propiedad'), ('C', 'Comercial'), ('F', 'Financiero'), ('A', 'Almacén')], max_length=45)),
                ('idcliente_representada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Cliente_Representada')),
            ],
        ),
    ]
