# Generated by Django 3.0.6 on 2020-10-01 15:54

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_representada',
            name='telefono_corp_1',
            field=phone_field.models.PhoneField(blank=True, help_text='Teléfono cliente fijo 1', max_length=31),
        ),
        migrations.AlterField(
            model_name='cliente_representada',
            name='telefono_corp_2',
            field=phone_field.models.PhoneField(blank=True, help_text='Teléfono cliente fijo 2', max_length=31),
        ),
        migrations.AlterField(
            model_name='contacto_cliente_representada',
            name='telefono_movil',
            field=phone_field.models.PhoneField(blank=True, help_text='Móvil del contacto', max_length=31),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='telefono_movil',
            field=phone_field.models.PhoneField(blank=True, help_text='Móvil del Contacto', max_length=31),
        ),
        migrations.AlterField(
            model_name='representada',
            name='telefono_corp_1',
            field=phone_field.models.PhoneField(blank=True, help_text='Teléfono fijo empresa 1', max_length=31),
        ),
        migrations.AlterField(
            model_name='representada',
            name='telefono_corp_2',
            field=phone_field.models.PhoneField(blank=True, help_text='Teléfono fijo empresa 2', max_length=31),
        ),
        migrations.AlterField(
            model_name='staff_ventas',
            name='telefono_movil',
            field=phone_field.models.PhoneField(blank=True, help_text='Móvil del contacto', max_length=31),
        ),
    ]
