# Generated by Django 3.0.6 on 2020-09-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_representada',
            name='email_corp',
            field=models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto_cliente_representada',
            name='departamento',
            field=models.CharField(choices=[('PA', 'Propiedad'), ('C', 'Comercial'), ('F', 'Financiero'), ('A', 'Almacén')], max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto_cliente_representada',
            name='idcliente_representada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada'),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='departamento',
            field=models.CharField(choices=[('PA', 'Propietario'), ('C', 'Comercial'), ('F', 'Financiero'), ('P', 'Producción')], max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='idrepresentada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada'),
        ),
        migrations.AlterField(
            model_name='representada',
            name='email_corp',
            field=models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stuff_ventas',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Representacion',
            fields=[
                ('idrepresentacion', models.AutoField(primary_key=True, serialize=False)),
                ('idcliente_representada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada')),
                ('idrepresentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada')),
                ('idstuff_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Stuff_Ventas')),
            ],
        ),
    ]
