# Generated by Django 3.0.6 on 2020-09-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_auto_20200922_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Ventas',
            fields=[
                ('idstaff_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('telefono_movil', models.IntegerField(blank=True)),
                ('email', models.EmailField(error_messages={'blank': 'Por favor, introduzca una dirección de correo valida', 'unique': 'Una cuenta con esta dirección de correo ya existe.'}, max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto_cliente_representada',
            name='idcliente_representada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada'),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='idrepresentada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada'),
        ),
        migrations.AlterField(
            model_name='representacion',
            name='idcliente_representada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada'),
        ),
        migrations.AlterField(
            model_name='representacion',
            name='idrepresentada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada'),
        ),
        migrations.AddField(
            model_name='representacion',
            name='idstaff_ventas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_login.Staff_Ventas'),
            preserve_default=False,
        ),
    ]
