# Generated by Django 3.0.6 on 2020-09-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_auto_20200922_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_representada',
            name='cif',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='contacto_cliente_representada',
            name='idcliente_representada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada'),
        ),
        migrations.AlterField(
            model_name='contacto_representada',
            name='idrepresentada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada'),
        ),
        migrations.AlterField(
            model_name='representacion',
            name='idcliente_representada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Cliente_Representada'),
        ),
        migrations.AlterField(
            model_name='representacion',
            name='idrepresentada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.Representada'),
        ),
        migrations.AlterField(
            model_name='representada',
            name='cif',
            field=models.CharField(max_length=45),
        ),
    ]
