# Generated by Django 3.0.6 on 2020-09-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0005_auto_20200923_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto_cliente_representada',
            name='idcliente_representada',
        ),
        migrations.RemoveField(
            model_name='contacto_representada',
            name='idrepresentada',
        ),
        migrations.RemoveField(
            model_name='representacion',
            name='idcliente_representada',
        ),
        migrations.RemoveField(
            model_name='representacion',
            name='idrepresentada',
        ),
        migrations.RemoveField(
            model_name='representacion',
            name='idstaff_ventas',
        ),
        migrations.DeleteModel(
            name='cliente_representada',
        ),
        migrations.DeleteModel(
            name='contacto_cliente_representada',
        ),
        migrations.DeleteModel(
            name='contacto_representada',
        ),
        migrations.DeleteModel(
            name='Representacion',
        ),
        migrations.DeleteModel(
            name='representada',
        ),
        migrations.DeleteModel(
            name='Staff_Ventas',
        ),
    ]
